export const TRY_AUTH = "TRY_AUTH";
export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const AUTH_REMOVE_TOKEN = "AUTH_REMOVE_TOKEN";

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const FETCH_USER_PHOTO_START = 'FETCH_USER_PHOTO_START';
export const FETCH_USER_PHOTO_SUCCESS = 'FETCH_USER_PHOTO_SUCCESS';
export const FETCH_USER_PHOTO_FAIL = 'FETCH_USER_PHOTO_FAIL';
export const USER_PHOTO_INIT = 'USER_PHOTO_INIT';

